Dockerfile: upgrade from Ubuntu Bionic (18.04) to Focal (20.04)
It fixes the following error when running slither:

  AttributeError: module 'typing' has no attribute '_SpecialForm'